// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2_jH8dzWGpp2uoQbv-QElHhBz0P2zrOg',
    appId: '1:382668842484:web:ac503b9113d479494685a1',
    messagingSenderId: '382668842484',
    projectId: 'foodlyfridge',
    authDomain: 'foodlyfridge.firebaseapp.com',
    storageBucket: 'foodlyfridge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUbY0NXxcxfe-_WFr3HGiYxlEmHO2_HU8',
    appId: '1:382668842484:android:1f70ffd4ebd1d94f4685a1',
    messagingSenderId: '382668842484',
    projectId: 'foodlyfridge',
    storageBucket: 'foodlyfridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwsHBcdDrAEeeUAFulBHIO9hrOl-vZ67g',
    appId: '1:382668842484:ios:78d62a0a12d012294685a1',
    messagingSenderId: '382668842484',
    projectId: 'foodlyfridge',
    storageBucket: 'foodlyfridge.firebasestorage.app',
    iosBundleId: 'com.example.foodlyfridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwsHBcdDrAEeeUAFulBHIO9hrOl-vZ67g',
    appId: '1:382668842484:ios:78d62a0a12d012294685a1',
    messagingSenderId: '382668842484',
    projectId: 'foodlyfridge',
    storageBucket: 'foodlyfridge.firebasestorage.app',
    iosBundleId: 'com.example.foodlyfridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2_jH8dzWGpp2uoQbv-QElHhBz0P2zrOg',
    appId: '1:382668842484:web:458801ce3ea692744685a1',
    messagingSenderId: '382668842484',
    projectId: 'foodlyfridge',
    authDomain: 'foodlyfridge.firebaseapp.com',
    storageBucket: 'foodlyfridge.firebasestorage.app',
  );
}
